[local_work]
path = "/home/lunamidori/nfs/Midori-AI-Github/Midori-AI-Mono-Repo/Experimentation/Swarm-o-codex/.environments/local-work"
created_at = "2025-10-31T01:48:37.200690+00:00"
last_updated = "2025-11-02T05:44:19.655860+00:00"
