name: Build and Upload PixelArch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 */2 * *'

jobs:

  push_arch_to_hub:
    name: Push Midori AI's PixelArch (Arch Linux) to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=latest
            type=raw,value=quartz

      - name: Build and push PixelArch Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Pixelarch-OS/pixelarch_os/
          file: ./Pixelarch-OS/pixelarch_os/arch_dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_arch_slim_to_hub:
    name: Push Midori AI's PixelArch Slim to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Install latest DockerSlim
        run: |
          curl -L https://github.com/slimtoolkit/slim/releases/latest/download/dist_linux.tar.gz | tar xz
          sudo mv dist_linux/* /usr/local/bin/

      - name: Build slim image from Dockerfile
        run: |
          slim build \
            --dockerfile ./Pixelarch-OS/pixelarch_os/arch_dockerfile \
            --tag lunamidori5/pixelarch:quartz-slim \
            ./Pixelarch-OS/pixelarch_os/

      - name: Push slim image to Docker Hub
        run: docker push lunamidori5/pixelarch:quartz-slim

  push_pixelarch_ver_to_hub:
    name: Push Midori AI's PixelArch to Docker Hub
    strategy:
      max-parallel: 4
      matrix:
        ver: [amethyst, topaz, emerald]
    runs-on: ubuntu-latest
    needs: push_arch_to_hub
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=${{ matrix.ver }}

      - name: Build and push PixelArch ${{ matrix.ver }} OS Docker Image
        uses: docker/build-push-action@master
        with:
          context: ./Pixelarch-OS/pixelarch_os/
          file: ./Pixelarch-OS/pixelarch_os/arch_dockerfile_${{ matrix.ver }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_pixelarch_subver_to_hub:
    name: Push SubVers of PixelArch to Docker Hub
    strategy:
      max-parallel: 1
      matrix:
        ver: [blackpixelarch/strikearch_emerald]
    runs-on: ubuntu-latest
    timeout-minutes: 360
    needs: push_arch_to_hub
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: false

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: lunamidori5/pixelarch
          tags: |
            type=raw,value=${{ matrix.ver }}

      - name: Build and push PixelArch ${{ matrix.ver }} OS Docker Image
        uses: docker/build-push-action@master
        continue-on-error: true
        with:
          context: ./Pixelarch-OS/pixelarch_os/subvers/
          file: ./Pixelarch-OS/pixelarch_os/subvers/${{ matrix.ver }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
